<?php
// Master Autoindex
// ionutvmi@gmail.com 
// Sep 2012
// master-land.net

include "inc/init.php";

$links[] = mai_img("arr.gif")." $lang->TOS";
include "header.php";

echo "<div class='title'>$lang->terms_of_service</div><div class='content'>".nl2br("YOU EXPRESSLY AGREE THAT USE OF THE SERVICE IS AT YOUR SOLE RISK AND THAT THE SERVICE IS PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS. $set->name, ITS AFFILIATES, AND THEIR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS (HEREINAFTER \"$set->name GROUP\") DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT.

$set->name GROUP MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE CONTENT PROVIDED ON OR VIA THE SERVICE AND $set->name GROUP ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, OMISSIONS OR INACCURACIES OF CONTENT OR SUBMISSIONS, (II) PERSONAL INJURY OR PROPERTY DAMAGE OF ANY NATURE RESULTING FROM YOUR ACCESS TO AND USE OF THE SERVICE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION THAT MAY BE CONTAINED THEREIN, (IV) ANY DELETION OF DATA OR INTERRUPTION OR DISCONTINUENCE OF TRANSMISSION TO OR FROM OR THROUGH THE SERVICE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, MALICIOUS CODE OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SERVICE BY ANY USER OR THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT OR SUBMISSIONS THAT MAY BE UPLOADED TO OR OTHERWISE MADE AVAILABLE THROUGH THE SERVICE.

$set->name GROUP IS NOT RESPONSIBLE FOR ANY CONTENT OR TRANSACTIONS THAT IS CONTAINED OR MAY BE AVAILABLE OUTSIDE THE SERVICE. $set->name GROUP MAKES NO REPRESENTATIONS, WARRANTEES, GUARANTEES OR ANY ENDORSEMENTS AS TO THE QUALITY, SUITABILITY, FUNCTIONALITY OR LEGALITY OF ANY PRODUCTS, SERVICES OR OTHER OFFERINGS THAT MAY BE ADVERTISED OR MADE AVAILABLE BY A THIRD PARTY THROUGH THE SERVICE OR WHICH MAY BE LINKED TO THE SERVICE SUCH AS IN ADVERTISING OR A SUBMISSION. ACCORDINGLY, $set->name GROUP WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR ANY TRANSACTION THAT MAY OCCUR BETWEEN YOU AND SUCH THIRD PARTIES AND YOU SHOULD ALWAYS USE PRUDENT JUDGMENT AND READ THE PRIVACY POLICIES ON WEBSITES OF SUCH THIRD PARTIES.

$set->name reserves the right to change any and all content, software and other items used or contained at $set->name and any services and applications offered through the $set->name site at any time without notice.")."</div>";

include "footer.php";